# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Build Python

on:
  push:
    branches: [ production, develop ]
  pull_request:
    branches: [ production ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Build Python Linux
      uses: eric2788/pyinstaller-build@master
      with:
        main: app
        artifact: ${{ github.event.repository.name }}
        python_version: 3.7
        use-dependencies: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: dist
        
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python Windows
        uses: eric2788/pyinstaller-build@master
        with:
          main: app
          artifact: ${{ github.event.repository.name }}
          python_version: 3.7
          use-dependencies: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: dist
  
  build_macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python MacOS
        uses: eric2788/pyinstaller-build@master
        with:
          main: app
          artifact: ${{ github.event.repository.name }}
          python_version: 3.7
          use-dependencies: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}@${{ github.sha }}
          path: dist